### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by rnijenhuis** [devopsconsulting/python-spynedelegate#2]
Running the test the following error occurred: AttributeError: 'module' object has no attribute 'client'

Use: from suds import client instead of import suds in test_with_suds.py.

**Comment by mj026** [comment]
Thnx @rnijenhuis for reporting. This is already fixed in the https://github.com/devopsconsulting/python-spynedelegate/tree/python3 branch. Will send a pull request on monday for this
